config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'about' => 'welcome#about'
  get 'getting_started' => 'welcome#help'
  devise_for :users
  resources :users, only: :show
  resources :registered_applications

  match '*any' => 'application#options', :via => [:options]
  namespace :api, defaults: { format: :json } do
    match 'create_event', to: 'events#create', via: [:options]
    resources :events, only: [:create]
  end

end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events, dependent: :destroy

  validates :name, length: {minimum: 2}, presence: true
  validates :url, length: {minimum: 5}, presence: true
  validates :user, presence: true
  validates_uniqueness_of :url, scope: :user_id
  validates_uniqueness_of :name, scope: :user_id

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  def new
    @registered_application = RegisteredApplication.new
    authorize @registered_application
  end

  def create
    @registered_application = RegisteredApplication.new(registered_application_params)
    authorize @registered_application
    @registered_application.user = current_user
    if @registered_application.save
      flash[:notice] = "Application was registered."
      redirect_to getting_started_path
    else
      flash[:error] = "There was an error registering the application.  Please try again."
      render :new
    end
  end

  def edit
    @registered_application = RegisteredApplication.friendly.find(params[:id])
    authorize @registered_application
  end

  def update
    @registered_application = RegisteredApplication.friendly.find(params[:id])
    authorize @registered_application
    if @registered_application.update_attributes(registered_application_params)
      flash[:notice] = "Application information was updated."
      redirect_to @registered_application
    else
      flash[:error] = "There was an error updating the application.  Please try again."
      render :new
    end
  end

  def index
    @registered_applications = current_user.registered_applications
    redirect_to getting_started_path if @registered_applications.count == 0
  end

  def show
    @registered_application = RegisteredApplication.friendly.find(params[:id])
    authorize @registered_application
    @events = @registered_application.events.group_by(&:name)
    render :show
  end

  def destroy
    @registered_application = RegisteredApplication.friendly.find(params[:id])
    authorize @registered_application
    if @registered_application.destroy
      flash[:notice] = "\"#{@registered_application.name}\" was deleted successfully."
      redirect_to registered_applications_path
    else
      flash[:error] = "There was an error deleting the application.  Please try again."
      redirect_to @registered_application
    end
  end

  private
    def registered_application_params
      params.require(:registered_application).permit(:name, :url, :user)
    end
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/views/registered_applications/_event.html.haml
%ul
  %li event.name

app/views/registered_applications/_form.html.haml
= form_for [registered_application] do |f|
  - if registered_application.errors.any?
    .alert.alert-danger
      %h4 
        There are
        = pluralize(registered_application.errors.count, "error")
      %ul
        - registered_application.errors.full_messages.each do |msg|
          %li
            = msg
  = f.label :name
  = f.text_field :name, autofocus: true, class: 'form-control', placeholder: "application Name"
  = f.label :url
  = f.text_field :url, class: 'form-control', placeholder: "application url"
  %br
  .form-group
    = f.submit "Save", class: 'btn btn-success'

app/views/registered_applications/edit.html.haml
- provide(:title, "Edit #{@registered_application.name}")
%h1 Edit #{@registered_application.name}
= render partial: 'form', locals: { registered_application: @registered_application }

app/views/registered_applications/index.html.haml
- provide(:title, "Applications")


.row
  .col-md-6
    %h3 Applications registered with Blocmetrics
    - @registered_applications.each do |application|
      .media
        .media-body
          %h4
            .media-heading
              %ul
                %li
                  = link_to application.name, application
                  - if policy(application).edit?
                    %p
                      = link_to "Edit", edit_registered_application_path(application)
                      = link_to "Delete", application, method: :delete, data: { confirm: 'Remove this application for sure?' }

app/views/registered_applications/new.html.haml
- provide(:title, "New Application")
%h1  Register a new application
= render partial: 'form', locals: { registered_application: @registered_application }

app/views/registered_applications/show.html.haml
- provide(:title, "#{@registered_application.name}")
= javascript_include_tag "//www.google.com/jsapi", "chartkick"

%h4
  = @registered_application.name
%p
  = @registered_application.url
= pie_chart @registered_application.events.group(:name).count
= line_chart @registered_application.events.group_by_day(:created_at).count

- if policy(@registered_application).edit? 
  %p
    = link_to "Edit", edit_registered_application_path
    = link_to "Delete", @registered_application, method: :delete, data: { confirm: 'Remove this application for sure?' }