config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'about' => 'welcome#about'
  get 'getting_started' => 'welcome#help'
  devise_for :users
  resources :users, only: :show
  resources :registered_applications

  match '*any' => 'application#options', :via => [:options]
  namespace :api, defaults: { format: :json } do
    match 'create_event', to: 'events#create', via: [:options]
    resources :events, only: [:create]
  end

end

app/views/layouts/_footer.html.haml
%footer
  .footer
    %small
      The <a href="http://www.bloc.io/">Blocmetrics project</a>
      by <a href="https://github.com/bgohman">Bradley Gohman</a>
    %ul
      .nav.navbar-nav.navbar-right
        %li
          = link_to "Home", root_path
        %li
          = link_to "About", about_path

app/views/layouts/_header.html.haml
%header
  .navbar.navbar-fixed-top
    .container
      %nav
        %ul
          .nav.navbar-nav.navbar-right
            - if current_user
              %li
                = link_to "Hello, #{current_user.name.capitalize}!", edit_user_registration_path(current_user)   
              %li
                = link_to "My Apps", registered_applications_path  
              %li
                = link_to "Add an App", new_registered_application_path 
              %li
                = link_to "Sign out", destroy_user_session_path, method: :delete
            - else
              %li
                = link_to "Sign in", new_user_session_path
              %li
                = link_to "Sign Up", new_user_registration_path
            %li
              = link_to "Help", getting_started_path 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
  
</body>
</html>